build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - go-scrutinizer-run

filter:
  excluded_paths:
    - 'test/*'
    - 'cmd/*'

checks:
  go: true
