build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
    tests:
      environment:
        php:
          version: 7.3
        variables:
          APP_ENV: 'test'
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover clover.xml
            coverage:
              file: clover.xml
              format: 'php-clover'

filter:
  excluded_paths:
    - 'tests/*'
    - 'bin/*'
checks:
  php: true
coding_style:
  php: {  }
