language: go
go:
  - '1.14'

install:
  - go mod download
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

script:
  - go test -v -race $(go list ./... | grep -v vendor)
  - golangci-lint run
