sudo: required
dist: trusty
group: stable

language: php
php:
  - '7.3'

env:
  global:
    - APP_ENV=test

services:
  - docker

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - bash ./build/build.sh

deploy:
  provider: script
  script: bash ./build/deploy.sh
  on:
    tags: true
    branch:
      - master
