sudo: required
dist: trusty
group: stable

language: php
php:
  - '7.2'

env:
  global:
    - APP_ENV=test

services:
  - docker

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/behat
  - docker build --pull --tag "swaggermock/swagger-mock" .
  - docker images

deploy:
  provider: script
  script: bash ./build/deploy.sh
  on:
    branch:
      - master
