version: '3.0'

services:
  swagger_mock:
    build:
      context: ./.dev
    environment:
      APP_ENV: dev
      SWAGGER_MOCK_SPECIFICATION_URL: '/app/examples/petstore.yaml'
      SWAGGER_MOCK_LOG_LEVEL: 'debug'
    volumes:
      - .:/app
      - composer_data:/var/run/composer
    ports:
      - "8080:8080"
      - "9001:9000"
