version: '3.0'

volumes:
  composer_data:

services:
  swagger_mock:
    container_name: swagger_mock
    build:
      context: ./.dev
    environment:
      APP_ENV: prod
      SWAGGER_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml'
      SWAGGER_MOCK_CACHE_STRATEGY: 'MD5'
      SWAGGER_MOCK_LOG_LEVEL: 'debug'
    volumes:
      - .:/app
      - composer_data:/var/run/composer
    ports:
      - "8080:8080"
      - "9001:9000"
