version: '3.0'

volumes:
  composer_data:

services:
  swagger_mock:
    container_name: swagger_mock
    image: swaggermock/swagger-mock
    environment:
      SWAGGER_MOCK_SPECIFICATION_URL: 'https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml'
      SWAGGER_MOCK_CACHE_STRATEGY: 'url_md5'
    ports:
      - "8080:8080"
