monolog:
  handlers:
    main:
      type: stream
      path: "php://stderr"
      level: debug
      excluded_404s:
        # regex: exclude all 404 errors from the logs
        - ^/
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
