parameters:
  locale: 'en'
  specification_url: '%env(SPECIFICATION_URL)%'

  type_parser_map:
    object: 'App\OpenAPI\Parsing\Type\Composite\ObjectTypeParser'
    array: 'App\OpenAPI\Parsing\Type\Composite\ArrayTypeParser'
    boolean: 'App\OpenAPI\Parsing\Type\Primitive\BooleanTypeParser'
    integer: 'App\OpenAPI\Parsing\Type\Primitive\IntegerTypeParser'
    number: 'App\OpenAPI\Parsing\Type\Primitive\NumberTypeParser'
    string: 'App\OpenAPI\Parsing\Type\Primitive\StringTypeParser'

  value_generator_map:
    App\Mock\Parameters\Schema\Type\Composite\ObjectType: 'App\Mock\Generation\Value\Composite\ObjectValueGenerator'
    App\Mock\Parameters\Schema\Type\Composite\ArrayType: 'App\Mock\Generation\Value\Composite\ArrayValueGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\BooleanType: 'App\Mock\Generation\Value\Primitive\RandomBooleanGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\IntegerType: 'App\Mock\Generation\Value\Primitive\FakerIntegerGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\NumberType: 'App\Mock\Generation\Value\Primitive\FakerNumberGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\StringType: 'App\Mock\Generation\Value\Primitive\FakerStringGenerator'


services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $endpointParser: '@App\OpenAPI\Parsing\EndpointParser'
      $responseParser: '@App\OpenAPI\Parsing\ResponseParser'
      $schemaParser: '@App\OpenAPI\Parsing\SchemaParser'

  App\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php}'

  App\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 48 }

  mock_parameters_collection:
    class: App\Mock\Parameters\MockParametersCollection
    public: true
    factory: ['@App\OpenAPI\SpecificationLoader', 'loadMockParameters']
    arguments:
      - '%kernel.project_dir%/tests/Resources/swagger-files/single-entity.yaml'

  App\Mock\MockParametersRepository:
    arguments:
      - '@mock_parameters_collection'

  type_parser_service_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator

  value_generator_service_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator

  App\OpenAPI\Parsing\TypeParserLocator:
    arguments:
      - '@type_parser_service_locator'
      - '%type_parser_map%'

  App\Mock\Generation\ValueGeneratorLocator:
    arguments:
      - '@value_generator_service_locator'
      - '%value_generator_map%'

  Faker\Generator:
    class: Faker\Generator
    factory: ['Faker\Factory', 'create']
