parameters:
  env(SWAGGER_MOCK_SPECIFICATION_URL): ''

services:
  specification_loader:
    public: true
    class: App\Tests\Utility\MockedSpecificationLoader
    factory:
      - 'App\Tests\Utility\MockedSpecificationLoader'
      - getInstance
    arguments:
      - '@App\OpenAPI\Loading\SpecificationFileLoader'

  App\OpenAPI\ErrorHandling\ErrorHandlerInterface: '@App\OpenAPI\ErrorHandling\ExceptionalErrorHandler'
