parameters:
  locale: 'en'
#  specification_url: '%env(SPECIFICATION_URL)%'
  specification_url: '%kernel.project_dir%/tests/Resources/swagger-files/value-generation.yaml'

  type_parser_map:
    object: 'App\OpenAPI\Parsing\Type\Composite\ObjectTypeParser'
    array: 'App\OpenAPI\Parsing\Type\Composite\ArrayTypeParser'
    boolean: 'App\OpenAPI\Parsing\Type\Primitive\BooleanTypeParser'
    integer: 'App\OpenAPI\Parsing\Type\Primitive\IntegerTypeParser'
    number: 'App\OpenAPI\Parsing\Type\Primitive\NumberTypeParser'
    string: 'App\OpenAPI\Parsing\Type\Primitive\StringTypeParser'

  value_generator_map:
    App\Mock\Parameters\Schema\Type\Composite\ObjectType: 'App\Mock\Generation\Value\Composite\ObjectValueGenerator'
    App\Mock\Parameters\Schema\Type\Composite\FreeFormObjectType: 'App\Mock\Generation\Value\Composite\FreeFormObjectValueGenerator'
    App\Mock\Parameters\Schema\Type\Composite\HashMapType: 'App\Mock\Generation\Value\Composite\HashMapValueGenerator'
    App\Mock\Parameters\Schema\Type\Composite\ArrayType: 'App\Mock\Generation\Value\Composite\ArrayValueGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\BooleanType: 'App\Mock\Generation\Value\Primitive\RandomBooleanGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\IntegerType: 'App\Mock\Generation\Value\Primitive\RandomIntegerGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\NumberType: 'App\Mock\Generation\Value\Primitive\RandomNumberGenerator'
    App\Mock\Parameters\Schema\Type\Primitive\StringType: 'App\Mock\Generation\Value\Primitive\FakerStringGenerator'


services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $endpointParser: '@App\OpenAPI\Parsing\EndpointParser'
      $responseParser: '@App\OpenAPI\Parsing\ResponseParser'
      $schemaParser: '@App\OpenAPI\Parsing\SchemaParser'
      $delegatingSchemaParser: '@App\OpenAPI\Parsing\Type\DelegatingSchemaParser'
      $resolvingSchemaParser: '@App\OpenAPI\Parsing\Type\ReferenceResolvingSchemaParser'

  App\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php}'

  App\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 48 }

  App\Mock\MockParametersRepository:
    arguments:
      - '@specification_loader'
      - '%specification_url%'

  specification_loader:
    class: App\OpenAPI\Loading\CachedSpecificationLoader
    arguments:
      - '@App\OpenAPI\Loading\SpecificationFileLoader'
      - '@specification_cache'

  specification_cache:
    class: Symfony\Component\Cache\Simple\FilesystemCache
    arguments:
      - 'openapi'
      - 0
      - '%kernel.project_dir%/var/file-cache'

  type_parser_service_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator

  value_generator_service_locator:
    class: Symfony\Component\DependencyInjection\ServiceLocator

  App\OpenAPI\Parsing\Type\TypeParserLocator:
    arguments:
      - '@type_parser_service_locator'
      - '%type_parser_map%'

  App\Mock\Generation\ValueGeneratorLocator:
    arguments:
      - '@value_generator_service_locator'
      - '%value_generator_map%'

  Faker\Generator:
    class: Faker\Generator
    factory: ['App\Faker\FakerGeneratorFactory', 'createGenerator']

  Negotiation\Negotiator:
    class: Negotiation\Negotiator
