parameters:
    locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php}'

  App\EventListener\RequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 48 }
