services:
  specification_loader:
    public: true
    class: App\Tests\Utility\MockedSpecificationLoader
    factory:
      - 'App\Tests\Utility\MockedSpecificationLoader'
      - getInstance
    arguments:
      - '@App\OpenAPI\Loading\SpecificationFileLoader'
