name: CI

on:
  push:
    branches: [ '*' ]
    branches-ignore: [ master ]
  pull_request:
    branches: [ '*' ]
    branches-ignore: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: go mod download

      - name: Build application
        run: |
          cd cmd/swagger-mock
          go build -v
          cd ../..

      - name: Set up linter
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

      - name: Run linter
        run: golangci-lint run

      - name: Run tests
        run: go test -v $(go list ./... | grep -v vendor)
