name: Build release binary

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64] #["386", amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Set release version env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - uses: wangyoucao577/go-release-action@master
        with:
          project_path: ./cmd/openapi-mock
          binary_name: openapi-mock
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ldflags: -w -s
